# IkeaShop/IkeaShop.Notifier/Dockerfile
# Use the official image as a parent image
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["IkeaShop.Notifier/IkeaShop.Notifier.csproj", "IkeaShop.Notifier/"]
RUN dotnet restore "IkeaShop.Notifier/IkeaShop.Notifier.csproj"
COPY . .
WORKDIR "/src/IkeaShop.Notifier"
RUN dotnet build "IkeaShop.Notifier.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "IkeaShop.Notifier.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "IkeaShop.Notifier.dll"]
