# IkeaShop/IkeaShop.Storage/Dockerfile
# Use the official image as a parent image
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["IkeaShop.Storage/IkeaShop.Storage.csproj", "IkeaShop.Storage/"]
RUN dotnet restore "IkeaShop.Storage/IkeaShop.Storage.csproj"
COPY . .
WORKDIR "/src/IkeaShop.Storage"
RUN dotnet build "IkeaShop.Storage.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "IkeaShop.Storage.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "IkeaShop.Storage.dll"]
