# IkeaShop/IkeaShop.OrderService/Dockerfile
# Use the official image as a parent image
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["IkeaShop.OrderService/IkeaShop.OrderService.csproj", "IkeaShop.OrderService/"]
RUN dotnet restore "IkeaShop.OrderService/IkeaShop.OrderService.csproj"
COPY . .
WORKDIR "/src/IkeaShop.OrderService"
RUN dotnet build "IkeaShop.OrderService.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "IkeaShop.OrderService.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "IkeaShop.OrderService.dll"]
